[build]
  publish = "Public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/pets/*"
  to = "/.netlify/functions/pets/:splat"
  status = 200

[[redirects]]
  from = "/api/pets"
  to = "/.netlify/functions/pets"
  status = 200

[[redirects]]
  from = "/api/adoptions/*"
  to = "/.netlify/functions/adoptions/:splat"
  status = 200

[[redirects]]
  from = "/api/adoptions"
  to = "/.netlify/functions/adoptions"
  status = 200
